project:
  type: website
  output-dir: docs

website:
  favicon: media/trsptlogo.png
  navbar:
    title: "Zay Chonnad"
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - coding.qmd
      - about.qmd

format:
  html:
    theme: styles.scss
    mainfont: Roboto Slab
    toc: true
    page-layout: full

editor: visual

