project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Zay Chonnad"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

